<?php

namespace app\admin\controller;

use think\Controller;
use think\Request;

use app\admin\model\Cate as CateModel;
use app\admin\model\Article as ArticleModel;
use app\admin\controller\Common;

class Cate extends Common
{
    public  function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $clist= CateModel::getLevelList();
        $this->assign('clist',$clist);
    }

    public function index()
    {
       return $this->fetch();
    }

    public function add($pid = ''){
        return $this->fetch('add', ['pid' => $pid]);
    }

    public function save(){
        if (Request::instance()->isPost()){
            $data = input('post.');
            if (CateModel::insert($data)){
                $this->success('添加成功');
            }else{
                $this->error('添加失败');
            }
        }
    }

    public function edit($id){
       $cate= CateModel::find($id);
        return $this->fetch('edit', ['cate' => $cate]);
    }
    public function update($id){
        if (Request::instance()->isPost()){
            $data = input('post.');
            if (CateModel::update($data,['id'=>$id])){
                $this->success('更新成功');
            }else{
                $this->error('更新失败');
            }
        }

    }

    public function del($id){
        CateModel::get(['pid'=>$id]);//
        ArticleModel::get(['cid'=>$id]);
        if (CateModel::get(['pid'=>$id])){
            $this->error('此分类下存在子分类，不可删除');
        }
        if ( ArticleModel::get(['cid'=>$id])){
            $this->error('此分类下存在文章，不可删除');
        }
        if(CateModel::get($id)->delete()){
            $this->success('删除成功');
        }else{
            $this->error('删除失败');
        }
    }

}
