<?php

namespace app\admin\controller;

use think\Controller;
use think\Loader;
use think\Request;
use think\Validate;
use app\admin\model\User as UserModel;
use app\admin\model\Group as GroupModel;
use app\admin\controller\Common;

class User extends Common
{
    public  function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $glist=GroupModel::where('status=1')->select();//输入用户组信息
       $this->assign('glist',$glist);
    }

    public function index($keyword='',$page=1)
    {
        $map=[];
        if ($keyword){
            $map['username|mobile|email']=['like',"%{$keyword}%"];
        }
        $ulist=UserModel::where($map)->order('id DESC')->paginate(15,false,['page',$page]);
        return $this->fetch('index',['ulist'=>$ulist,'keyword'=>$keyword]);
    }
    public function edit($id){
        $user=UserModel::find($id);
        return $this->fetch('edit',['user'=>$user]);
    }
    public function update($id){
        $data= Request::instance()->post();
        $validate = $this->validate($data, 'User');
        if ($validate!=true){
            $this->error($validate);
        }else{
            $data['password']=$data['password'];
            if (model('User')->allowField(true)->save($data, ['id' => $id])) {
                $this->success('更新成功');
            } else {
                $this->error('更新失败');
            }

        }

    }

    public function add(){
        return $this->fetch();
    }
    public function save(){
        if (Request::instance()->isPost()){
            $data= Request::instance()->post();
            $validate = $this->validate($data, 'User');
            if ($validate!=true){
                $this->error($validate);
            }else{
                $data['password']=$data['password'];
                $UserModel=new UserModel();
                if ($UserModel -> allowField(true) -> save($data)) {
                    $this->success('保存成功');
                } else {
                    $this->error('保存失败');
                }
            }

        }
//        $data  = $this->request->post();
//        $data=input('post.');

    }

    public function del($id){
        if ( UserModel::destroy($id)){
            $this->success('删除成功');
        }else{
            $this->error('删除失败');
        }
    }
}
